twig:
    paths:
        '%kernel.project_dir%/templates/Themes/%current_theme%': ~
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        application: '%application%'